name: CD Workflow

on:
  push:
    branches: [main, develop]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Terraform Apply
        run: terraform apply --auto-approve